import { Trade } from "@/types";

export const MOCK_TRADES: Trade[] = [
  {
    id: "1",
    pair: "BTC/USDT",
    direction: "Long",
    status: "Win",
    date: "2026-01-20T14:30:00Z",
    entryPrice: 42500.50,
    stopLoss: 41800.00,
    takeProfit: 44500.00,
    exitPrice: 44500.00,
    rrPredicted: 2.85,
    rrRealized: 2.85,
    setupType: "SFP",
    confluences: ["Daily Open", "Bullish Divergence", "Level Claim"],
    notes: "Perfect SFP at the range low. Strong reaction from the daily open.",
    tags: ["Swing", "High Conviction"]
  },
  {
    id: "2",
    pair: "ETH/USDT",
    direction: "Short",
    status: "Loss",
    date: "2026-01-21T09:15:00Z",
    entryPrice: 2450.00,
    stopLoss: 2510.00,
    takeProfit: 2200.00,
    exitPrice: 2510.00,
    rrPredicted: 4.16,
    rrRealized: -1.0,
    setupType: "Range Rotation",
    confluences: ["Range EQ Rejection", "VWAP Deviation"],
    notes: "Stopped out quickly. Market had more momentum than expected.",
    tags: ["Scalp"]
  },
  {
    id: "3",
    pair: "SOL/USDT",
    direction: "Long",
    status: "Open",
    date: "2026-01-23T08:00:00Z",
    entryPrice: 95.20,
    stopLoss: 91.50,
    takeProfit: 108.00,
    rrPredicted: 3.45,
    setupType: "Break & Retest",
    confluences: ["Golden Pocket", "Previous Day High", "Volume Spike"],
    notes: "Retesting the breakout level. Looking for a push towards $108.",
    tags: ["Swing"]
  },
  {
    id: "4",
    pair: "LINK/USDT",
    direction: "Short",
    status: "Breakeven",
    date: "2026-01-22T16:45:00Z",
    entryPrice: 18.50,
    stopLoss: 19.20,
    takeProfit: 16.00,
    exitPrice: 18.50,
    rrPredicted: 3.57,
    rrRealized: 0,
    setupType: "Golden Pocket",
    confluences: ["Fib 0.618", "Resistance Zone"],
    notes: "Moved stop to breakeven after first target. Hit BE during overnight volatility.",
    tags: ["Day Trade"]
  },
  {
    id: "5",
    pair: "BTC/USDT",
    direction: "Long",
    status: "Win",
    date: "2026-01-19T20:00:00Z",
    entryPrice: 41200.00,
    stopLoss: 40500.00,
    takeProfit: 43000.00,
    exitPrice: 42800.00,
    rrPredicted: 2.57,
    rrRealized: 2.28,
    setupType: "SFP",
    confluences: ["Monday Low SFP", "H4 Demand Zone"],
    notes: "Closed slightly early before TP as momentum started to fade.",
    tags: ["Swing"]
  }
];
